### ISSUE TITLE
Add Gradle or Maven support

### ISSUE THREAD

**Issue by JhnBrunelle** [WEMarsSoftware/MissionControl#11]
We have org.json dependency that right now we have to manually install. As the project gets more complex, we'll need video and map dependencies.

Someone should integrate either Maven or Gradle to manage our dependencies and builds, especially since the goal is to output binary executables rather than jars (for speed!). I vote for Gradle since it has really good Intellij integration, and is more modern.

Links:
[Gradle](https://gradle.org/)
[Installing Gradle](https://docs.gradle.org/current/userguide/installation.html)
[Gradle for NPM Users](https://seesparkbox.com/foundry/gradle_for_npm_users) <- mainly for me 

[Maven](https://maven.apache.org/)
[Installing Maven](https://maven.apache.org/install.html)

**Comment by JhnBrunelle** [comment]
Update: This is going to be a huge rework, I'll stow this away until we get a stable GUI and then add this in. 

Ultimately, we should use gradle as it seems to be the more modern one!

**Comment by joshuakarbi** [comment]
JInput controller/gamepad library dependency coming soon.
