### ISSUE TITLE
Video feed into GUI

### ISSUE THREAD

**Issue by JhnBrunelle** [WEMarsSoftware/MissionControl#3]
Multiple Camera Feed

We have 4 cameras to read
1) Main Feed (360p 15fps), which is the front camera of the rover
2) Arm Feed(144p, 15fps )
3) 2 under body cameras (360p, 1fps)

2 and 3 do NOT need to be active all the time.

**Comment by joshuakarbi** [comment]
@JhnBrunelle I can put these 3 feeds into it's own window/controller. Will make it easy to put in its own thread later

**Comment by JhnBrunelle** [comment]
@joshuakarbi Good idea, let's try putting all three into one controller first, separate from the main controller, and if needed later we can sperate into three separate ones, one for each feed
